### ISSUE TITLE
Debian Taiwan template

### ISSUE THREAD

**Issue by szlin** [linux-taiwan/www.debian.org.tw#5]
從jekyll 資源[1](https://github.com/jekyll/jekyll/wiki/Themes)找了幾個 themes.

目前挑了 4 個 themes 出來, 大家有什麼建議嗎?
1. https://volny.github.io/stylish-portfolio-jekyll/
2. http://daktilo.github.io/
3. http://shikherverma.com/
4. https://damianeoloan.github.io/JekyllOrg/

**Comment by bcbcarl** [comment]
2 或 3 不錯啊。

**Comment by chusiang** [comment]
個人比較偏愛 1, 2。

**Comment by szlin** [comment]
http://arkadianriver.com/ 感覺也不錯

**Comment by bcbcarl** [comment]
先隨便選一個，讓首頁有出現呢？

**Comment by szlin** [comment]
ok. 我下週先刻一版出來.

**Comment by szlin** [comment]
http://szlin.github.io
還在刻一些東西, 過幾天再push上來.

**Comment by kidwm** [comment]
Looks great!

**Comment by bcbcarl** [comment]
看起來很棒！

**Comment by chusiang** [comment]
@szlin ++

**Comment by szlin** [comment]
有 web 大大能夠協助搬移嗎? 
想要把資料從 https://github.com/szlin/szlin.github.io 搬過來, 但是一直無法成功.

**Comment by bcbcarl** [comment]
@szlin 你是說用 `szlin.github.io` 的內容蓋掉 `www.debian.org.tw` 嗎？

**Comment by szlin** [comment]
是的！，我試了幾次都無法成功建立網頁，術業有專攻，看有沒有好心人可以幫忙解惑
