### ISSUE TITLE
取回 debian.org.tw 網域

### ISSUE THREAD

**Issue by bcbcarl** [linux-taiwan/www.debian.org.tw#7]
此網域目前在「天狼星」手上，目的是替「大愛徵信社」做 SEO。

大愛徵信社已承諾要把網域交回來，會請「天狼星」與小弟接洽。

**Comment by bcbcarl** [comment]
@szlin 他們有換信箱。

**Comment by chusiang** [comment]
咦？又換一家了耶。

```
$ whois debian.org.tw
Domain Name: debian.org.tw
Registrant:
新北市徵信商業同業公會
New TAIPEI City DETECTIVE BUSINESS ASSOCIATION
11F., No.130, Sec. 4, Chongyang Rd., Sanchong Dist., New Taipei City 241

   Contact:
      DAAI   domain@mail.sirius-design.com.tw
      TEL:  02-29899177
      FAX:  02-29895014

   Record expires on 2017-07-18 (YYYY-MM-DD)
   Record created on 2016-07-09 (YYYY-MM-DD)


Registration Service Provider: APT
```

**Comment by szlin** [comment]
天狼星廣告設計沒有換信箱, mail 是一樣的, 只是不回我.

看來找業主才有用

感謝 Carl & Rudi 協助

我會匯款給天狼星廣告設計先拿回 Domain name.

**Comment by szlin** [comment]
最新消息:
- 關於Domain name 轉移

我已經匯錢過去給天狼星.

但他們負責人本週不在, 要下週才能處理 domain name 讓渡的問題.

這方面我會繼續追.
- 關於 Domain name owner

我會先拿回來, 再連絡ocf.tw 看能不能由他們接手 (感謝 czchen建議)

**Comment by chihchun** [comment]
我建議你先聯絡 ocf 做後續網域名稱承接，免得要轉移數次

SZ Lin notifications@github.com 於 2016年8月23日 週二 09:58 寫道：

**Comment by kidwm** [comment]
我上次問 OCF 關於代管域名的事宜，他們是說沒有人可以處理，不知道現在狀況有沒有改變。

**Comment by szlin** [comment]
今天遇到 Bob, 他說OCF下週開會 會進行討論. 

為了盡速把 domain name 拿回來, 避免節外生枝, 所以我會請天狼星先掛我這邊. 屆時我再轉出去. 
- domain name  掛在法人底下比較適合.

**Comment by kidwm** [comment]
必要的話可以問問 gandi.net 台北辦公室能不能提供支援。

**Comment by szlin** [comment]
跟各位 update: 我們已經成功將 domain name 取回.

感謝各位出力的朋友: Rudiger, $4, Appier- Joe, CZ.

最後要感謝 OCF 以及最熱心的 Carl

**Comment by szlin** [comment]
跟各位 update: 我們已經成功將 domain name 取回.

感謝各位出力的朋友: Rudiger, $4, Appier- Joe, CZ Chen 等等

最後要感謝 OCF 以及最熱心的 Carl. 
有你們的協助, 才能將 domain name 那麼順利的拿回來.

未來 domain name 將委由 OCF 代管, 再度 謝謝 OCF 對社群的支援!

**Comment by chusiang** [comment]
可喜可賀！

**Comment by JackSkyAP** [comment]
可以請問花了多少$？交涉過程要找誰？ 謝謝。
